### ISSUE TITLE
Unable to process less files named close.less

### ISSUE THREAD

**Issue by dcdieci** [metaskills/less-rails#104]
I just upgraded to rails 4.2.2 and got the following error.

```
/app/views/layouts/application.html.erb where line #9 raised:

invalid byte sequence in UTF-8
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

trace
less-rails (2.7.0) lib/less/rails/import_processor.rb:23:in `scan'
less-rails (2.7.0) lib/less/rails/import_processor.rb:23:in `depend_on'
less-rails (2.7.0) lib/less/rails/import_processor.rb:27:in `block in depend_on'
less-rails (2.7.0) lib/less/rails/import_processor.rb:24:in `each'
less-rails (2.7.0) lib/less/rails/import_processor.rb:24:in `depend_on'
less-rails (2.7.0) lib/less/rails/import_processor.rb:18:in `evaluate'
tilt (1.4.1) lib/tilt/template.rb:103:in `render'
```

I have bootstrap less in folder vendor. One of bootstraps files is called. close.less so I have in my application
@import "close";

As soon as I remove or rename this file I don't get the error any longer.

**Comment by maxd** [comment]
Could you please provide minimal project for reproduce problem?

**Comment by dcdieci** [comment]
@maxd I just setup a new rails app and the issue does not occur in there.
So I removed bootstrap files in the project where the error occurs and added bootstrap's less files again.

and my application.css.less looks like this
```
@import "icons.css";
@import "sprite.css";
//@import "date_picker";

@import "font.css";
@import "helpers";

@import "style";
@import "resorts-pane";
@import "accommodations";

@import "custom_marker";
@import "custom-mixins";

//=================================================== bootstrap ========================================================

// Core variables and mixins
@import "variables";
@import "mixins";

// Reset
@import "normalize";
@import "print";

// Core CSS
@import "scaffolding";
@import "type";
@import "code";
@import "grid";
@import "tables";
@import "forms";
@import "buttons";

// Utility classes
@import "utilities";
@import "responsive-utilities";

// Components
@import "component-animations";
@import "glyphicons";
@import "dropdowns";
@import "button-groups";
@import "input-groups";
@import "navs";
@import "navbar";
@import "breadcrumbs";
@import "pagination";
@import "pager";
@import "labels";
@import "badges";
@import "jumbotron";
@import "thumbnails";
@import "alerts";
@import "progress-bars";
@import "media";
@import "list-group";
@import "panels";
@import "wells";
@import "close";
@import "modals";
@import "tooltip";
@import "popovers";
@import "carousel";

//================================================ end bootstrap =======================================================
@import "vendor/assets/stylesheets/bootstrap-slider";
@import "vendor/assets/stylesheets/typeahead";

```

->
invalid byte sequence in UTF-8

As soon as I remove @import "close"; the error is gone.
I am confused

**Comment by dcdieci** [comment]
I deleted the entire assets dir and added the files again, now it works.
